=head1 NAME

App::Rad::Tutorial - Command line applications made easy!

=head1 OVERVIEW

App::Rad provides a framework for rapid (and fun) development of command line applications. This tutorial will guide you through the basic features of App::Rad programs so you can develop your own applications in no time!

=head1 YOUR FIRST APPLICATION!

Getting started with App::Rad is really easy: just create a file (let's name it "myapp.pl") and write:

    use App::Rad;
    App::Rad->run();

That's it! Your program already works and you can use it on the command line. Let's try it:

    [user@host]$ ./myapp.pl
    Usage: myapp.pl command [arguments]
    
    Available Commands:
        help    show syntax and available commands

